### ISSUE TITLE
SSO error 403 / Access denied

### ISSUE THREAD

**Issue by andrewleech** [sodelalbert/Withings2Garmin#4]
Hi, new user here - thanks for providing this tool!

As previously reported in https://github.com/sodelalbert/Withings2Garmin/issues/2 there's an issue with the token response page, but the workaround there worked fine for me.

Once that was done, I ran into the following error:
```
Withings: Get Access Token
Withings: Refresh Access Token
Withings: Get Measurements
   Measurements received
Traceback (most recent call last):
  File "/home/corona/Withings2Garmin/./sync.py", line 126, in <module>
    main()
  File "/home/corona/Withings2Garmin/./sync.py", line 55, in main
    sync(**opts.__dict__)
  File "/home/corona/Withings2Garmin/./sync.py", line 118, in sync
    session = garmin.login(garmin_username, garmin_password)
  File "/home/corona/Withings2Garmin/garmin.py", line 144, in login
    session = self._get_session(email=username, password=password)
  File "/home/corona/Withings2Garmin/garmin.py", line 87, in _get_session
    raise APIException("SSO error %s %s" % (ssoResp.status_code, ssoResp.text))
NameError: name 'APIException' is not defined
```

APIException doesn't exist anywhere here and is not a builtin type in python 3.9.5 at least.

I replaced the `APIException ` usages with ValueError and wrote the 403 response html to a file, it looks like this:

![image](https://user-images.githubusercontent.com/3318786/122631577-edd7f580-d10f-11eb-9f70-11de4ec3243b.png)

Any idea what might case this?

**Comment by dave986** [comment]
Same issue. I suppose Garmin was not happy about the recent phishing attack, so they closed all the gates.

**Comment by laurentserena** [comment]
same error..any hope for a work around?

**Comment by andrewleech** [comment]
I actually switched to this alternate tool, it was working at the time at least https://github.com/jaroslawhartman/withings-sync

**Comment by laurentserena** [comment]
> I actually switched to this alternate tool, it was working at the time at least https://github.com/jaroslawhartman/withings-sync
It s still working fine!!! Thank you so much for the advice
